# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('japanese', models.CharField(max_length=255)),
                ('updated_date', models.DateField()),
                ('domain_company', models.CharField(max_length=255)),
                ('representative', models.CharField(max_length=255)),
            ],
        ),
    ]
