# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_site', models.IntegerField()),
                ('to_site', models.IntegerField()),
                ('link_position', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_company', models.CharField(max_length=255)),
                ('updated_date', models.DateField()),
                ('host', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('site_title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('japanese', models.CharField(max_length=255)),
                ('server', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SiteComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
