# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_link_server_site_sitecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='representative',
        ),
    ]
