# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_domain_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ftp_server',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
