# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_server_ftp_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='ftp_server',
        ),
        migrations.AddField(
            model_name='server',
            name='db_pass',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ftp_pass',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='payment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
