# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20151231_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.IntegerField()),
                ('url', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('is_representative', models.BooleanField(default=False)),
            ],
        ),
    ]
