# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_domaindetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='domain_company_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
