# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_domain_domain_company_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='login_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='login_pass',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
