# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20151231_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='update_method',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='update_method',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
