# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20160130_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='group',
            new_name='group_name',
        ),
    ]
