# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20160131_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecomment',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitecomment',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
