# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20160131_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='from_site',
        ),
        migrations.AddField(
            model_name='link',
            name='site_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='to_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='to_site',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
