# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_group_payment_setting_domain_setting_link_setting_server_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('site_id', models.IntegerField()),
                ('created_date', models.DateField()),
            ],
        ),
    ]
