# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='server_company',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
