# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_domain_server_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
