# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_server_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='login_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
